# DO NOT REMOVE OR MODIFY #
version: '1.1.4'
# ----------------------- #

#The Y location the egg item will spawn at
egg-start-y: 180.0

#Type of particle, see: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
particle-type: 'FLAME'

#The number of particles to spawn
particle-amount: 4

#The length of the particle trail
particle-length: 6.0

#Extra value of the particle
particle-extra: 0.0

#Particle offsets
particle-offset-x: 0.25
particle-offset-y: 0.0
particle-offset-z: 0.25

#How often to spawn the particles (in ticks)
particle-interval: 1

#Number of lightning entities to spawn on egg land
lightning-amount: 4

#Drop type (egg, chest, chance, all). Option to drop a loot chest instead of an egg.
#Loot items are defined in loot.yml via command /ded addloot
#The 'all' type places every item defined in the loot.yml into the chest one time each.
drop-type: egg
#If chance, what is the percent chance of spawning a chest?(0 - 100)
chest-spawn-chance: 20
#Want a custom title for the loot chest? Set it here.
loot-chest-title: 'Loot Chest'

#Number of items in a loot chest
min-loot: 2
max-loot: 6

#Set a custom name and lore for the egg item (optional)
#NOTE: Only eggs broken/dropped in the end world without
#existing ItemMeta will receive the below name/lore.
egg-name: ''
egg-lore: []

#Respawn dragon on death? (delay is in seconds)
respawn: false
respawn-delay: 300

#Give the dragon a custom name, or not, your choice.
#If more than one name, the name will be chosen at random.
#Names do support color/format codes i.e. &4 (red).
#Set to: dragon-names: [] for none.
dragon-names:
- 'Endy'
- 'Falcor'
- 'Haiku'