# DO NOT REMOVE OR MODIFY #
version: 2
# ----------------------- #

perform-update-checks: true

# All data involving the particle effects displayed after the death of the Ender Dragon
Particles:
    # The Y location the reward object will spawn at
    egg-start-y: 180.0
    
    # Type of particle, see: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
    type: 'FLAME'
    
    # The number of particles to spawn per particle iteration
    amount: 4
    
    # Extra data of the particle (Most are not affected by this value)
    extra: 0
    
    # The particle offsets for each direction
    x-offset: 0.001
    y-offset: 0.001
    z-offset: 0.001
    
    # The speed multiplier at which particles will be spawned (how fast they will descend)
    speed-multiplier: 1
    
    # The amount of particle lines that will animate from the ceiling
    stream-count: 6
    
    # How often to spawn the particles (in ticks)
    interval: 1
    
    # Advanced particle functionality! DO NOT TOUCH UNLESS YOU UNDERSTAND WHAT THIS DOES
    Advanced:
        # A pre-defined mathematical shape for the particles to be displayed in
        # (Available: "BALL", "HELIX", "OPEN_END_HELIX", "CUSTOM")
        preset-shape: 'OPEN_END_HELIX'
        
        # The mathematical expression in which particles will be spawned along the x coordinate
        x-coord-expression: 'cos(theta)'
        
        # The mathematical expression in which particles will be spawned along the z coordinate
        z-coord-expression: 'sin(theta)'

# Number of lightning entities to spawn on egg land
lightning-amount: 4

# Respawn dragon on join? (delay is in seconds)
respawn-on-join: false
join-respawn-delay: 60

# Respawn dragon on death? (delay is in seconds)
respawn-on-death: true
death-respawn-delay: 300

# Whether the countdown will run even when out of the end
countdown-across-world: false

# Announcement message animation
announce-messages:
- '&6Dragon respawning in &e%formatted-time%'
- '&eDragon respawning in &6%formatted-time%'