name: DragonEggDrop
main: com.ninjaguild.dragoneggdrop.DragonEggDrop
version: 1.4.0-BETA2
author: 2008Choco

commands:
  dragoneggdrop:
    usage: /<command> [help]
    aliases: [ded]
  dragontemplate:
    usage: /<command> <template> <view|edit>
    aliases: [dragontemplates, template, templates]

permissions:
  dragoneggdrop.*:
    description: Allow access to all commands in dragoneggdrop
    default: op
    children:
      dragoneggdrop.help: true
      dragoneggdrop.reload: true
      dragoneggdrop.addloot: true
      dragoneggdrop.template.*: true
  
  dragoneggdrop.template.*:
    description: Allow access to the details of all loaded dragon templates
    default: op
    children:
      dragoneggdrop.template.list: true
      dragoneggdrop.template.info: true
      dragoneggdrop.template.edit.*: true
      
  dragoneggdrop.template.edit.*:
    description: Allow access to data modifications for dragon templates
    default: op
    children:
      dragoneggdrop.template.edit.addloot: true
      dragoneggdrop.template.edit.set: true