name: DragonEggDrop
main: com.ninjaguild.dragoneggdrop.DragonEggDrop
version: 1.4.0
author: 2008Choco

commands:
  dragoneggdrop:
    usage: /<command> [help]
    aliases: [ded]
  dragontemplate:
    usage: /<command>
    aliases: [dragontemplates, template, templates]

permissions:
  dragoneggdrop.help:
    default: op
  dragoneggdrop.reload:
    default: op
  dragoneggdrop.addloot:
    default: op