name: DragonEggDrop
main: com.ninjaguild.dragoneggdrop.DragonEggDrop
version: 1.2.3
author: NinjaStix

commands:
  dragoneggdrop:
    usage: /<command> [help]
    aliases: [ded]

permissions:
  dragoneggdrop.help:
    default: op
  dragoneggdrop.reload:
    default: op
  dragoneggdrop.addloot:
    default: op