name: DragonEggDrop
main: com.ninjaguild.dragoneggdrop.DragonEggDrop
version: 1.1.5
author: NinjaStix

commands:
  dragoneggdrop:
    usage: /dragoneggdrop [help]
    aliases: [ded]

permissions:
  dragoneggdrop.help:
    default: op
  dragoneggdrop.reload:
    default: op
  dragoneggdrop.addloot:
    default: op