name: DragonEggDrop
main: com.ninjaguild.dragoneggdrop.DragonEggDrop
version: 1.1.0
author: NinjaStix

commands:
  dragoneggdrop:
    usage: /dragoneggdrop [help]
    aliases: [ded]

permissions:
  dragoneggdrop.reload:
    default: op