name: DragonEggDrop
main: com.ninjaguild.dragoneggdrop.DragonEggDrop
version: ${project.version}
author: 2008Choco

commands:
  dragoneggdrop:
    description: The main DragonEggDrop command
    usage: /<command> [help]
    aliases: [ded]
  dragonspawn:
    description: A command to force respawning a dragon
    usage: /<command>
  dragontemplate:
    description: A utility command to control dragon templates
    usage: /<command> <template> <view|edit>
    aliases: [dragontemplates, template, templates]

permissions:
  dragoneggdrop.*:
    description: Allow access to all commands in dragoneggdrop
    default: op
    children:
      dragoneggdrop.help: true
      dragoneggdrop.reload: true
      dragoneggdrop.spawn: true
      dragoneggdrop.template.*: true

  dragoneggdrop.spawn:
    description: Allow access to the ender dragon spawn command
    default: op

  dragoneggdrop.template.*:
    description: Allow access to the details of all loaded dragon templates
    default: op
    children:
      dragoneggdrop.template.list: true
      dragoneggdrop.template.info: true
      dragoneggdrop.template.edit.*: true
      
  dragoneggdrop.template.edit.*:
    description: Allow access to data modifications for dragon templates
    default: op
    children:
      dragoneggdrop.template.edit.addloot: true
      dragoneggdrop.template.edit.set: true